# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=adept
      - POSTGRES_PASSWORD=adeptpassword
      - POSTGRES_DB=adeptdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: