# This is a config for E2B sandbox template.
# You can use template ID (akg67ob4ipqre21jz6it) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("akg67ob4ipqre21jz6it") # Sync sandbox
# sandbox = await AsyncSandbox.create("akg67ob4ipqre21jz6it") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('akg67ob4ipqre21jz6it')

team_id = "4980e10a-b041-4516-b194-15456ed27cbc"
dockerfile = "e2b.Dockerfile"
template_id = "akg67ob4ipqre21jz6it"
